spring.datasource.url=jdbc:mysql://javaapp004-server.mysql.database.azure.com:3306/studentdb?sslMode=REQUIRED
spring.datasource.username=goykjrhzno
spring.datasource.password=Shre1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

server.port=8080
