spring.datasource.url=jdbc:sqlserver://javaapp001.database.windows.net:1433;database=demo_1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
spring.datasource.username=javaapp001-admin@javaapp001
spring.datasource.password=Demo@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

server.port=8080
