# ===============================
# SQL Server Database Configuration
# ===============================

spring.datasource.url=jdbc:sqlserver://javaapp002.database.windows.net:1433;database=webappdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

spring.datasource.username=javaapp002@javaapp002
spring.datasource.password=App@1234

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Thymeleaf
# ===============================

spring.thymeleaf.cache=false

server.port=8080
